name: Java CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
     branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  Build and test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checout code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK  
        uses: actions/setup-java@v4.2.2
        with: 
          java-version: '21'
          distribution: 'temurin'
