name: Java CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
     branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  Java-project-71:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/app
        
    steps: 
      - name: Checout code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK  
        uses: actions/setup-java@v4.2.2
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.7'

      - name: Start build
        run: make build
          
      - name: Start test
        run: make test

      - name: Start report
        run: make report
          

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
         # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
            # The report file must be there, otherwise Code Climate won't find it
            workingDirectory: ${{github.workspace}}/app
            coverageCommand: make report
            coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
