  name: GitHub Actions
  run-name: Hexlet java-project-71
  on: [push]
  jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Publish code coverage
          uses: paambaati/codeclimate-action@v6.0.0
          env: 
             CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
             JACOCO_SOURCE_PATH: src/main/java
          with:
              coverageCommand: make report
              coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/html/index.html:jacoco
        - run: ./gradlew checkstyleMain
        - run: ./gradlew test
        - run: ./gradlew build