  name: GitHub Actions
  run-name: Hexlet java-project-71
  on: [push, pull_request]
  jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - run: |
            ls ${{ github.workspace }}
        - run: ./gradlew checkstyleMain
        - run: ./gradlew test
        - run: ./gradlew build
        - name: Publish code coverage
          uses: paambaati/codeclimate-action@v5.0.0
          env: 
             CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
             JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
          with:
              coverageCommand: make report
              coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
