  name: GitHub Actions
  run-name: Hexlet java-project-71
  on: 
    - push
    - pull_request
  jobs:
    say_hello:
      runs-on: ubuntu-latest
      steps:
        - run: echo hello actions
    init:
      runs-on: ubuntu-latest
    buld:
      needs: init
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3
          with:
            gradle-version: '8.5'

        - run: |
            ls -la ${{ github.workspace }} 
       
          
        - name: Build with Gradle Wrapper
          run: ${{github.workspace}}/app/gradlew build
      test:    
       needs: build
       runs-on: ubuntu-latest
        
        - name: Publish code coverage
          uses: paambaati/codeclimate-action@v5.0.0
          env: 
             CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
             JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
          with:
              coverageCommand: make report
              coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
